# Generated by Django 4.0.6 on 2022-08-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Cultivator',
        ),
    ]
