# Generated by Django 4.0.6 on 2022-08-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_num',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivator',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
