# Generated by Django 4.0.6 on 2022-08-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_post_post_num_alter_cultivator_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thread_title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
