# Generated by Django 4.0.6 on 2022-09-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=512)),
                ('weight_grams', models.DecimalField(decimal_places=1, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='ContamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kingdom', models.CharField(choices=[('fungus', 'Fungus'), ('animal', 'Animal'), ('bacteria', 'Bacteria')], max_length=255)),
                ('cause', models.TextField(blank=True, null=True)),
                ('prevention', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.TextField(blank=True, null=True)),
                ('yield_dry', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date_created', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('volume_per_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_per_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonotubSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length_inch', models.FloatField(max_length=10)),
                ('width_inch', models.FloatField(max_length=10)),
                ('height_inch', models.FloatField(max_length=10)),
                ('sub_depth_inch', models.FloatField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('recipe', models.TextField()),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ingredient_mtm', models.ManyToManyField(blank=True, to='cultivation.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('notes', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Syringe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_purchased', models.DateField()),
                ('crop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivation.crop')),
                ('strain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.strain')),
            ],
        ),
        migrations.CreateModel(
            name='SpawnBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(choices=[('bag', 'Bag'), ('jar', 'Jar')], default='bag', max_length=255)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_contaminated', models.BooleanField(default=False)),
                ('date_spawned', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('recipe_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.recipe')),
                ('syringe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.syringe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.recipetype'),
        ),
        migrations.CreateModel(
            name='Monotub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_spawn', models.DecimalField(decimal_places=2, max_digits=16)),
                ('volume_bulk', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sub_depth_inch', models.FloatField(default=3.0, max_length=8)),
                ('is_cased', models.BooleanField(default=False)),
                ('tub_code', models.CharField(blank=True, max_length=8, null=True)),
                ('is_contaminated', models.BooleanField(default=False)),
                ('date_fruited', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('bag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.spawnbag')),
                ('monotub_size_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.monotubsize')),
                ('recipe_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidCultureJar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.recipe')),
                ('strain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.strain')),
            ],
        ),
        migrations.CreateModel(
            name='Flush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_wet', models.DecimalField(decimal_places=2, max_digits=16)),
                ('partial_flush', models.BooleanField(default=False)),
                ('is_dunked', models.BooleanField(default=True)),
                ('date_harvested', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('monotub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.monotub')),
            ],
            options={
                'verbose_name_plural': 'Flushes',
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='strain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.strain'),
        ),
        migrations.AddField(
            model_name='crop',
            name='tek_mtm',
            field=models.ManyToManyField(blank=True, to='cultivation.tek'),
        ),
        migrations.CreateModel(
            name='Contam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(choices=[('green', 'Green'), ('pink', 'Pink'), ('black', 'Black'), ('white', 'White'), ('grey', 'Grey'), ('wet', 'Wet'), ('gnats', 'Gnats'), ('mycogone', 'Mycogone'), ('cobweb', 'Cobweb')], max_length=255)),
                ('contam_img', models.ImageField(blank=True, null=True, upload_to='photos/contam')),
                ('description', models.TextField(blank=True, null=True)),
                ('bag_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.spawnbag')),
                ('lc_jar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.liquidculturejar')),
                ('tub_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.monotub')),
                ('type_guess_mtm', models.ManyToManyField(to='cultivation.contamtype')),
            ],
        ),
    ]
