# Generated by Django 4.0.6 on 2022-09-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='thing',
        ),
    ]
